ALTER TABLE IF EXISTS public."user"
  ADD COLUMN IF NOT EXISTS "clientType" TEXT NOT NULL DEFAULT 'particular',
  ADD COLUMN IF NOT EXISTS "companyName" TEXT,
  ADD COLUMN IF NOT EXISTS "companyRut" TEXT,
  ADD COLUMN IF NOT EXISTS "companyEmail" TEXT,
  ADD COLUMN IF NOT EXISTS "companyPhone" TEXT,
  ADD COLUMN IF NOT EXISTS "companyAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "isApproved" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE IF EXISTS neon_auth."user"
  ADD COLUMN IF NOT EXISTS "clientType" TEXT NOT NULL DEFAULT 'particular',
  ADD COLUMN IF NOT EXISTS "companyName" TEXT,
  ADD COLUMN IF NOT EXISTS "companyRut" TEXT,
  ADD COLUMN IF NOT EXISTS "companyEmail" TEXT,
  ADD COLUMN IF NOT EXISTS "companyPhone" TEXT,
  ADD COLUMN IF NOT EXISTS "companyAddress" TEXT,
  ADD COLUMN IF NOT EXISTS "isApproved" BOOLEAN NOT NULL DEFAULT false;
